// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/remote/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus_State int32

const (
	ExecutionStatus_UNKNOWN   ExecutionStatus_State = 0
	ExecutionStatus_STARTED   ExecutionStatus_State = 1
	ExecutionStatus_RUNNING   ExecutionStatus_State = 2
	ExecutionStatus_COMPLETED ExecutionStatus_State = 3
	ExecutionStatus_FAILED    ExecutionStatus_State = 4
	ExecutionStatus_CANCELLED ExecutionStatus_State = 5
)

// Enum value maps for ExecutionStatus_State.
var (
	ExecutionStatus_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTED",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELLED",
	}
	ExecutionStatus_State_value = map[string]int32{
		"UNKNOWN":   0,
		"STARTED":   1,
		"RUNNING":   2,
		"COMPLETED": 3,
		"FAILED":    4,
		"CANCELLED": 5,
	}
)

func (x ExecutionStatus_State) Enum() *ExecutionStatus_State {
	p := new(ExecutionStatus_State)
	*p = x
	return p
}

func (x ExecutionStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_remote_proto_agent_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus_State) Type() protoreflect.EnumType {
	return &file_pkg_remote_proto_agent_proto_enumTypes[0]
}

func (x ExecutionStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus_State.Descriptor instead.
func (ExecutionStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{8, 0}
}

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_Status = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_Status = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_Status = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_Status = 3
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_remote_proto_agent_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_remote_proto_agent_proto_enumTypes[1]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{11, 0}
}

// ExecuteRequest is sent by the client to initiate or control execution
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteRequest_Start
	//	*ExecuteRequest_Cancel
	//	*ExecuteRequest_Heartbeat
	Payload       isExecuteRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetPayload() isExecuteRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteRequest) GetStart() *StartExecution {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecuteRequest) GetCancel() *CancelExecution {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ExecuteRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isExecuteRequest_Payload interface {
	isExecuteRequest_Payload()
}

type ExecuteRequest_Start struct {
	Start *StartExecution `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecuteRequest_Cancel struct {
	Cancel *CancelExecution `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

type ExecuteRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*ExecuteRequest_Start) isExecuteRequest_Payload() {}

func (*ExecuteRequest_Cancel) isExecuteRequest_Payload() {}

func (*ExecuteRequest_Heartbeat) isExecuteRequest_Payload() {}

// StartExecution contains initial execution parameters
type StartExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                        // Unique identifier for this execution
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                        // Session identifier for grouping requests
	AgentName     string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`                                                        // Name of the agent to execute
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`                                                                                 // Input prompt for the agent
	AuthToken     string                 `protobuf:"bytes,5,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`                                                        // Authentication token
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartExecution) Reset() {
	*x = StartExecution{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExecution) ProtoMessage() {}

func (x *StartExecution) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExecution.ProtoReflect.Descriptor instead.
func (*StartExecution) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StartExecution) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StartExecution) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartExecution) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *StartExecution) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *StartExecution) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *StartExecution) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CancelExecution requests termination of ongoing execution
type CancelExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecution) Reset() {
	*x = CancelExecution{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecution) ProtoMessage() {}

func (x *CancelExecution) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecution.ProtoReflect.Descriptor instead.
func (*CancelExecution) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CancelExecution) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Heartbeat keeps the connection alive
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ExecuteResponse is streamed by the server during execution
type ExecuteResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteResponse_Output
	//	*ExecuteResponse_Error
	//	*ExecuteResponse_Tokens
	//	*ExecuteResponse_Status
	//	*ExecuteResponse_HeartbeatAck
	Payload       isExecuteResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteResponse) GetPayload() isExecuteResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetOutput() *OutputChunk {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ExecuteResponse) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ExecuteResponse) GetTokens() *TokenUsageUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Tokens); ok {
			return x.Tokens
		}
	}
	return nil
}

func (x *ExecuteResponse) GetStatus() *ExecutionStatus {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ExecuteResponse) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

type isExecuteResponse_Payload interface {
	isExecuteResponse_Payload()
}

type ExecuteResponse_Output struct {
	Output *OutputChunk `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type ExecuteResponse_Error struct {
	Error *ErrorMessage `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ExecuteResponse_Tokens struct {
	Tokens *TokenUsageUpdate `protobuf:"bytes,4,opt,name=tokens,proto3,oneof"`
}

type ExecuteResponse_Status struct {
	Status *ExecutionStatus `protobuf:"bytes,5,opt,name=status,proto3,oneof"`
}

type ExecuteResponse_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,6,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

func (*ExecuteResponse_Output) isExecuteResponse_Payload() {}

func (*ExecuteResponse_Error) isExecuteResponse_Payload() {}

func (*ExecuteResponse_Tokens) isExecuteResponse_Payload() {}

func (*ExecuteResponse_Status) isExecuteResponse_Payload() {}

func (*ExecuteResponse_HeartbeatAck) isExecuteResponse_Payload() {}

// OutputChunk contains a piece of agent output
type OutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputChunk.ProtoReflect.Descriptor instead.
func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *OutputChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OutputChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ErrorMessage contains error information
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Fatal         bool                   `protobuf:"varint,3,opt,name=fatal,proto3" json:"fatal,omitempty"` // If true, execution has terminated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetFatal() bool {
	if x != nil {
		return x.Fatal
	}
	return false
}

// TokenUsageUpdate provides real-time token usage information
type TokenUsageUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheRead     int32                  `protobuf:"varint,3,opt,name=cache_read,json=cacheRead,proto3" json:"cache_read,omitempty"`
	CacheWrite    int32                  `protobuf:"varint,4,opt,name=cache_write,json=cacheWrite,proto3" json:"cache_write,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,5,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,6,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	IsFinal       bool                   `protobuf:"varint,7,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // True if this is the final count (not an estimate)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsageUpdate) Reset() {
	*x = TokenUsageUpdate{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsageUpdate) ProtoMessage() {}

func (x *TokenUsageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsageUpdate.ProtoReflect.Descriptor instead.
func (*TokenUsageUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TokenUsageUpdate) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsageUpdate) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsageUpdate) GetCacheRead() int32 {
	if x != nil {
		return x.CacheRead
	}
	return 0
}

func (x *TokenUsageUpdate) GetCacheWrite() int32 {
	if x != nil {
		return x.CacheWrite
	}
	return 0
}

func (x *TokenUsageUpdate) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *TokenUsageUpdate) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *TokenUsageUpdate) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// ExecutionStatus indicates the state of execution
type ExecutionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ExecutionStatus_State  `protobuf:"varint,1,opt,name=state,proto3,enum=remote.ExecutionStatus_State" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStatus) Reset() {
	*x = ExecutionStatus{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStatus) ProtoMessage() {}

func (x *ExecutionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStatus.ProtoReflect.Descriptor instead.
func (*ExecutionStatus) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionStatus) GetState() ExecutionStatus_State {
	if x != nil {
		return x.State
	}
	return ExecutionStatus_UNKNOWN
}

func (x *ExecutionStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatAck acknowledges a heartbeat
type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthCheckRequest verifies server availability
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// HealthCheckResponse returns server health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=remote.HealthCheckResponse_Status" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_remote_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_remote_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_remote_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_remote_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/remote/proto/agent.proto\x12\x06remote\"\xb1\x01\n" +
	"\x0eExecuteRequest\x12.\n" +
	"\x05start\x18\x01 \x01(\v2\x16.remote.StartExecutionH\x00R\x05start\x121\n" +
	"\x06cancel\x18\x02 \x01(\v2\x17.remote.CancelExecutionH\x00R\x06cancel\x121\n" +
	"\theartbeat\x18\x03 \x01(\v2\x11.remote.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xa1\x02\n" +
	"\x0eStartExecution\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x05 \x01(\tR\tauthToken\x12@\n" +
	"\bmetadata\x18\x06 \x03(\v2$.remote.StartExecution.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x0fCancelExecution\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xbc\x02\n" +
	"\x0fExecuteResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\x06output\x18\x02 \x01(\v2\x13.remote.OutputChunkH\x00R\x06output\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x14.remote.ErrorMessageH\x00R\x05error\x122\n" +
	"\x06tokens\x18\x04 \x01(\v2\x18.remote.TokenUsageUpdateH\x00R\x06tokens\x121\n" +
	"\x06status\x18\x05 \x01(\v2\x17.remote.ExecutionStatusH\x00R\x06status\x12;\n" +
	"\rheartbeat_ack\x18\x06 \x01(\v2\x14.remote.HeartbeatAckH\x00R\fheartbeatAckB\t\n" +
	"\apayload\"?\n" +
	"\vOutputChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"R\n" +
	"\fErrorMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05fatal\x18\x03 \x01(\bR\x05fatal\"\xf3\x01\n" +
	"\x10TokenUsageUpdate\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12\x1d\n" +
	"\n" +
	"cache_read\x18\x03 \x01(\x05R\tcacheRead\x12\x1f\n" +
	"\vcache_write\x18\x04 \x01(\x05R\n" +
	"cacheWrite\x12!\n" +
	"\ftotal_tokens\x18\x05 \x01(\x05R\vtotalTokens\x12\x19\n" +
	"\bcost_usd\x18\x06 \x01(\x01R\acostUsd\x12\x19\n" +
	"\bis_final\x18\a \x01(\bR\aisFinal\"\xd8\x01\n" +
	"\x0fExecutionStatus\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.remote.ExecutionStatus.StateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"X\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05\",\n" +
	"\fHeartbeatAck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xb5\x01\n" +
	"\x13HealthCheckResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".remote.HealthCheckResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032\x96\x01\n" +
	"\fAgentService\x12>\n" +
	"\aExecute\x12\x16.remote.ExecuteRequest\x1a\x17.remote.ExecuteResponse(\x010\x01\x12F\n" +
	"\vHealthCheck\x12\x1a.remote.HealthCheckRequest\x1a\x1b.remote.HealthCheckResponseB6Z4github.com/rasmuselmersson/opencode/pkg/remote/protob\x06proto3"

var (
	file_pkg_remote_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_remote_proto_agent_proto_rawDescData []byte
)

func file_pkg_remote_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_remote_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_remote_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_remote_proto_agent_proto_rawDesc), len(file_pkg_remote_proto_agent_proto_rawDesc)))
	})
	return file_pkg_remote_proto_agent_proto_rawDescData
}

var file_pkg_remote_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_remote_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_remote_proto_agent_proto_goTypes = []any{
	(ExecutionStatus_State)(0),      // 0: remote.ExecutionStatus.State
	(HealthCheckResponse_Status)(0), // 1: remote.HealthCheckResponse.Status
	(*ExecuteRequest)(nil),          // 2: remote.ExecuteRequest
	(*StartExecution)(nil),          // 3: remote.StartExecution
	(*CancelExecution)(nil),         // 4: remote.CancelExecution
	(*Heartbeat)(nil),               // 5: remote.Heartbeat
	(*ExecuteResponse)(nil),         // 6: remote.ExecuteResponse
	(*OutputChunk)(nil),             // 7: remote.OutputChunk
	(*ErrorMessage)(nil),            // 8: remote.ErrorMessage
	(*TokenUsageUpdate)(nil),        // 9: remote.TokenUsageUpdate
	(*ExecutionStatus)(nil),         // 10: remote.ExecutionStatus
	(*HeartbeatAck)(nil),            // 11: remote.HeartbeatAck
	(*HealthCheckRequest)(nil),      // 12: remote.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 13: remote.HealthCheckResponse
	nil,                             // 14: remote.StartExecution.MetadataEntry
}
var file_pkg_remote_proto_agent_proto_depIdxs = []int32{
	3,  // 0: remote.ExecuteRequest.start:type_name -> remote.StartExecution
	4,  // 1: remote.ExecuteRequest.cancel:type_name -> remote.CancelExecution
	5,  // 2: remote.ExecuteRequest.heartbeat:type_name -> remote.Heartbeat
	14, // 3: remote.StartExecution.metadata:type_name -> remote.StartExecution.MetadataEntry
	7,  // 4: remote.ExecuteResponse.output:type_name -> remote.OutputChunk
	8,  // 5: remote.ExecuteResponse.error:type_name -> remote.ErrorMessage
	9,  // 6: remote.ExecuteResponse.tokens:type_name -> remote.TokenUsageUpdate
	10, // 7: remote.ExecuteResponse.status:type_name -> remote.ExecutionStatus
	11, // 8: remote.ExecuteResponse.heartbeat_ack:type_name -> remote.HeartbeatAck
	0,  // 9: remote.ExecutionStatus.state:type_name -> remote.ExecutionStatus.State
	1,  // 10: remote.HealthCheckResponse.status:type_name -> remote.HealthCheckResponse.Status
	2,  // 11: remote.AgentService.Execute:input_type -> remote.ExecuteRequest
	12, // 12: remote.AgentService.HealthCheck:input_type -> remote.HealthCheckRequest
	6,  // 13: remote.AgentService.Execute:output_type -> remote.ExecuteResponse
	13, // 14: remote.AgentService.HealthCheck:output_type -> remote.HealthCheckResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_remote_proto_agent_proto_init() }
func file_pkg_remote_proto_agent_proto_init() {
	if File_pkg_remote_proto_agent_proto != nil {
		return
	}
	file_pkg_remote_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecuteRequest_Start)(nil),
		(*ExecuteRequest_Cancel)(nil),
		(*ExecuteRequest_Heartbeat)(nil),
	}
	file_pkg_remote_proto_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ExecuteResponse_Output)(nil),
		(*ExecuteResponse_Error)(nil),
		(*ExecuteResponse_Tokens)(nil),
		(*ExecuteResponse_Status)(nil),
		(*ExecuteResponse_HeartbeatAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_remote_proto_agent_proto_rawDesc), len(file_pkg_remote_proto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_remote_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_remote_proto_agent_proto_depIdxs,
		EnumInfos:         file_pkg_remote_proto_agent_proto_enumTypes,
		MessageInfos:      file_pkg_remote_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_remote_proto_agent_proto = out.File
	file_pkg_remote_proto_agent_proto_goTypes = nil
	file_pkg_remote_proto_agent_proto_depIdxs = nil
}
